version: '3.1'

services:

  # Sistema de base de datos basado en mysql
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    ports:
      - 3306:3306

  # Interfaz gráfica para gestión de bases de datos
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'notSecureChangeMe'

  # Servidor web para hostear phpmyadmin
  web:
    image: nginx
    volumes:
      - /home/vicente/containers/backend/Cliente/dist:/usr/share/nginx/html:ro
    ports:
      - 80:80
    environment:
      - NGINX_HOST=puerta.net
      - NGINX_PORT=80
